# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-22 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("oauth2_provider", "0004_merge")]

    operations = [
        migrations.AlterIndexTogether(
            name="refreshtoken", index_together=set([("application", "user")])
        )
    ]
