# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0005_add_index_to_refresh_token'),
        ('oauth2_provider', '0006_auto_20171214_2232'),
    ]

    operations = [
    ]
